name: Format + Lint + Test + Build + Deploy Vite ReactJS App

on:
  push:
    branches:
      - master

jobs:
  format-and-lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Format Code
      - name: Format and Lint the code in the repository
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Install and setup Bun
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      # Install project dependencies  
      - name: Install dependencies
        run: bun install
      # Build and bundle project
      - name: Build Projects
        run: bun run build
      # Deploy project
      - name: Deploy to GH packages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
